name: 'Ansible Lint'
description: 'Lint ansible files'
inputs:
  dir:
    required: false
    default: '.'
    description: 'Path to serach for files'
runs:
  using: 'docker'
  image: 'docker://quay.io/elastx/ci-ansible-lint:6.0.2'
